name: Build Advanced INstaller Visual Studio Project (AIPROJ)
on: [workflow_dispatch]
jobs:
  aiproj-demo:
    runs-on: windows-latest
    name: Build Visual Studio Project (aiproj)
    
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
        
      - name: Deploy latest advinst version
        uses: 1amnoob/Saraff.Twain.DS.DirectX/Saraff.Twain.DS.DirectX.Installer_x86
        
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      
      - name: Build app
        run: msbuild ${{ github.workspace }}\MyEdit\MyEdit.sln
        
      - name: Publish setup artifact
        uses: actions/upload-artifact@v4
        with:
          name: MyEdit-Setup
          path: ${{ github.workspace }}\MyEdit\MyEdit Installer\MyEdit Installer-SetupFiles\MyEdit Installer.msi 
